### ISSUE TITLE
AttributeError: 'BinaryConvolution2D' object has no attribute 'dim_ordering'

### ISSUE THREAD

**Issue by felix-liuying** [DingKe/BinaryNet#1]
I clone the project in my keras to run,but appeared following error:

/home/felix/PycharmProjects/BinaryNet/binary_layers.py:127: UserWarning: Update your `BinaryConvolution2D` call to the Keras 2 API: `BinaryConvolution2D(128, (3, 3), padding="same", use_bias=False, name="conv1", input_shape=(3, 32, 32...)`
  super(BinaryConvolution2D, self).__init__(nb_filter, nb_row, nb_col, **kwargs)
Traceback (most recent call last):
  File "/home/felix/PycharmProjects/BinaryNet/mnist_cnn.py", line 77, in <module>
    border_mode='same', bias=bias, name='conv1'))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 433, in add
    layer(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 558, in __call__
    self.build(input_shapes[0])
  File "/home/felix/PycharmProjects/BinaryNet/binary_layers.py", line 130, in build
    if self.dim_ordering == 'th':
AttributeError: 'BinaryConvolution2D' object has no attribute 'dim_ordering'

i need to amend where?

**Comment by DingKe** [comment]
This repo is not maintained anymore. You can use[this repo](https://github.com/DingKe/nn_playground/tree/master/binarynet) for keras 2.0+ support.
Sorry for the inconvenience.
